apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cserver-deployment
spec:
  selector:
    matchLabels:
      app: cserver
  replicas: 1
  template:
    metadata:
      labels:
        app: cserver
    spec:
      containers:
      - name: cserver
        image: gcr.io/coinkitalpha/cserver
        ports:
        - containerPort: 8000
        - containerPort: 9000
