apiVersion: v1
kind: Service
metadata:
  name: cserviceX
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      name: http
      targetPort: 8000
    - port: 9000
      name: p2p
      targetPort: 9000
    - port: 3000
      name: proxy
      targetPort: 3000
    - port: 4000
      name: tracker
      targetPort: 4000
  selector:
    app: cserverX
